name: 'Test inputs'

on:
  workflow_dispatch:
    inputs:
      bucketname:
        required: true
        type: string
        description: "name of the bucket"
      labels:
        required: true
        type: string
        description: "labels"

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false

    - name: Verify terraform
      run: terraform init
    
    - name: Verify terraform
      run: terraform plan
      env:
        TF_VAR_bucketname: ${{ inputs.bucketname }}
        TF_VAR_labels: ${{ inputs.labels }}